### ISSUE TITLE
documentation for setting up the wallets is wrong

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfta-trader#18]
wallet.network="TEST"  crashes:
```
ERROR    | jumpscale.tools.errorhandler.errorhandler:_handle_exception:55 - TypeError: unsupported operand type(s) for -: 'Network' and 'str'
Traceback (most recent call last):
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/bin/jsng", line 11, in <module>
    load_entry_point('js-ng', 'console_scripts', 'jsng')()
    └ <function load_entry_point at 0x1075f9290>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x107b8a680>
           └ <Command run>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x107771b90>
         │    └ <function Command.invoke at 0x107b8f050>
         └ <Command run>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'command': None}
           │   │      │    │           └ <click.core.Context object at 0x107771b90>
           │   │      │    └ <function run at 0x107bb29e0>
           │   │      └ <Command run>
           │   └ <function Context.invoke at 0x107b8a170>
           └ <click.core.Context object at 0x107771b90>
  File "/Users/rob/Library/Caches/pypoetry/virtualenvs/js-sdk-Dbu3Jec3-py3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
           │         │       └ {'command': None}
           │         └ ()
           └ <function run at 0x107bb29e0>
```

**Comment by robvanmieghem** [comment]
1235c9195b230266a8960da13880d6c311b8c7c5
